### PR TITLE
Add build.gradle and wrappers.

### PR DESCRIPTION
**Pull request by songy23**
Also fix compilation errors on checked exceptions.

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you @songy23 for the *gradle* and wrappers!

I don't think we should change those exceptions, the program builds just fine and the purpose here is to catch any exception regardless of type and then increase the errors found. Catching only a SQLException will ignore others. Please revert that change.

**Comment by songy23** [comment]
> I don't think we should change those exceptions, the program builds just fine and the purpose here is to catch any exception regardless of type and then increase the errors found. Catching only a SQLException will ignore others. Please revert that change.

Unfortunately that doesn't work with Gradle build. Gradle will fail with this message if a checked exception is thrown but it's not in the method signature:
```bash
error: unreported exception Exception; must be caught or declared to be thrown
            throw e;
            ^
```
In addition the `throw e;` statement also appears as an error on my IDE, so I don't think this would build. Another option here is to log the exception instead of throwing it.

**Comment by songy23** [comment]
> Unfortunately that doesn't work with Gradle build. Gradle will fail with this message if a checked exception is thrown but it's not in the method signature:

Just found this problem is only with JDK 1.6 or before. Updating Gradle to only work with JDK 1.7+ resolved the problem.
